### ISSUE TITLE
cabal haddock does not find figures

### ISSUE THREAD

**Issue by ingo-sander** [forsyde/forsyde-atom#20]
cabal haddock has problems with the figures on my machine:

...
  21% ( 29 /141) in 'ForSyDe.Atom.MoC.SDF'
 100% (  3 /  3) in 'ForSyDe.Atom.Skeleton.Vector.Interface'
  43% ( 75 /174) in 'ForSyDe.Atom.Skeleton.Vector'
 100% ( 52 / 52) in 'ForSyDe.Atom'
Warning: ForSyDe.Atom.MoC.DE: could not find link destinations for:
    event
Warning: ForSyDe.Atom.MoC.CT: could not find link destinations for:
    event
Documentation created: dist/doc/html/forsyde-atom/index.html
cabal: filepath wildcard 'includes/figs/*.png' does not match any files.

**Comment by ugeorge** [comment]
At the moment you need to type in `make sandbox` which, apart from creating a sandbox, it sets up all the dependencies as well in their right path (e.g. fetches the forsyde-tikz package from GitHub). Most likely the figures were not generated because forsyde-tikz was missing. 

I am currently creating a new make rule for dependencies and documenting it.
